### ISSUE TITLE
Interface file permissions are written as rw-------

### ISSUE THREAD

**Issue by mchubby** [nMustaki/debinterface#14]
debinterface relies on `tempfile.NamedTemporaryFile` to create the file.
Debian does not set such permissions at install time.

The 0600 permissions are hardwired in NamedTemporaryFile [by design](http://stackoverflow.com/questions/10541760/can-i-set-the-umask-for-tempfile-namedtemporaryfile-in-python).

**Comment by nMustaki** [comment]
Good catch ! We should chmod to 0644.
Again, do you want to submit a PR ?


--
/*
** "What do you despise? By this you are truly known."
**	from Manual of Muad'Dib by the Princess Irulan.
*/
