### ISSUE TITLE
Only one DNS server is retained

### ISSUE THREAD

**Issue by kierank** [nMustaki/debinterface#21]
Thank you for this excellent fork.

One thing we have noticed is that if "dns-nameservers" contains multiple DNS entries (e.g "dns-nameservers 4.2.2.1 4.2.2.2"), only one of them is retained. This isn't the end of the world of course.

I'm not sure what the best way to fix this is since there isn't a type for string with spaces of IP addresses but if you have any ideas please let me know.

**Comment by nMustaki** [comment]
Hi @kierank,

Thanks for the thanks and thanks for making me discover yet another syntax !

I guess we could craft a new validation type "array", with a "subtype" key of "IP", but that sounds hacky. Ideally, I would prefer integrating with a real validation framework, but I don't know which one right now.

If you want to work with me on this that would be great !

**Comment by kierank** [comment]
Hi,

My colleague @jude188 has written a patch for this.

Kieran

**Comment by nMustaki** [comment]
That's great, many thanks !

**Comment by kierank** [comment]
Fixed by @Jude188
