### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Interfaces'

### ISSUE THREAD

**Issue by underdpt** [nMustaki/debinterface#6]
Hi, 

I'm trying to use your debinterface fork, but am facing an error:

``` python
Python 2.7.3 (default, Jun 20 2016, 16:18:47)
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import debinterface
>>> adapters = debinterface.Interfaces().adapters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Interfaces'
>>>
```

I'm using python 2.7.3 on raspbian, but also happens on windows (with test interfaces.txt file).

**Comment by underdpt** [comment]
I found it:
```python
from debinterface.interfaces import Interfaces
```
and then
```python
adapters = Interfaces.adapters
```
I think the README should be updated.

**Comment by nMustaki** [comment]
You're completly right, I must create a real documentation !


--
/*
** "What do you despise? By this you are truly known."
**	from Manual of Muad'Dib by the Princess Irulan.
*/

**Comment by nMustaki** [comment]
Documentation is now pushed to Read the doc and class can be imported like the example.
Just have to complete the doc now ;-)
