### ISSUE TITLE
adapter: Fix option parsing

### ISSUE THREAD

**Issue by nMustaki** [nMustaki/debinterface#8]
Noticed by @underdpt, we must include the PR made by @julianscheel on the parent repo.
@julianscheel if you want to open a new PR here you're welcome, otherwise I'll do it.

**Comment by julianscheel** [comment]
@nMustaki sure, let me add a new pull request. Is this repository some kind of the new home of debinterface? Seems the original one is a somewhat dead...

**Comment by nMustaki** [comment]
Yes, the parent was not responding, so I "took over". It is pushed to pypi too.

**Comment by nMustaki** [comment]
Thanks again for your speedy pull requests !
